cal/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
cal/urls.py

Created by Jimmy Gitonga on 2010-12-28.
Copyright (c) 2010 __MyCompanyName__. All rights reserved.
"""
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^(?P<year>\d{4})/$', CalYearView.as_view(), name='year'),
    url(r'^month/$', CalMonthView.as_view(), name='month'),
    url(r'^month/(?P<year>\d{4})/(?P<month>\d+)/$',
        CalMonthView.as_view(), name='month'),
    url(r'^month/(?P<year>\d{4})/(?P<month>\d+)/(?P<change>\w{4})/$', CalMonthView.as_view(), name='month'),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

from rest_framework_jwt.views import obtain_jwt_token
from dokeza.users.api.views import get_jwt_token
from .views import HomeView, AboutView, HelpView, ContactView, CalendarView, Root, TagIndexView

from annotation import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^help/$', HelpView.as_view(), name='help'),
    url(r'^news/', include('posts.urls', namespace='posts')),
    url(r'^contacts/$', ContactView.as_view(), name='contacts'),
    url(r'^bills/', include('bills.urls', namespace='bills')),
    url(r'^public-participation/', include('public_participation.urls', namespace='public_participation')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('dokeza.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # These are the regular urls.

    # url(r'^annotations/', include('annotation.urls',
    #                               namespace='annotator')),
    url(r'^bills/', include('bills.urls', namespace='bills')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^categories/$', TagIndexView.as_view(), name='categories'),

    url(r'^calendar/', include('cal.urls', namespace='kalenda')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # Annotation URLS
    url(r"^annon_root/$", views.root, name="root"),
    url(r"^annotations/(?P<pk>.+)/?$",
        views.read_update_delete, name="read_update_delete"),
    url(r"^annotations/?$", views.index_create, name="index_create"),
    url(r"^search/?$", views.search, name="search"),
    url(r"^demo/?$", views.DemoView.as_view(), name="demo"),

    # ------- These are the API urls ------------
    # Authentication APIs
    url(r'^api/$', Root),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/auth/token/$', get_jwt_token),
    url(r'^api/users/', include('dokeza.users.api.urls', namespace='users-api')),

    # Access APIs
    url(r'^api/bills/', include('bills.api.urls', namespace='bills-api')),
    url(r'^api/news/', include('posts.api.urls', namespace='posts-api')),
    url(r'^api/comments/', include('comments.api.urls', namespace='comments-api')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

dokeza/users/api/urls.py
from django.conf.urls import url

from .views import UserCreateAPIView, UserLoginAPIView
# UserDetailAPIView, UserUpdateAPIView, UserRedirectAPIView UserListAPIView


urlpatterns = [
    # url(r'^$', UserListAPIView.as_view(), name='list'),
    url(r'^login/$', UserLoginAPIView.as_view(), name='login'),
    url(r'^register/$', UserCreateAPIView.as_view(), name='register'),

    # url(r'^(?P<username>[\w.@+-]+)/$', UserDetailAPIView.as_view(), name='detail'),
    # url(r'^~redirect/$', UserRedirectAPIView.as_view(), name='redirect'),
    # url(r'^~update/$', UserUpdateAPIView.as_view(), name='update'),
]

dokeza/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from bills.views import BillDraftView
from posts.views import PetitionDraftView
from . import views


urlpatterns = [
    # URL pattern for the UserListView
    url(r'^$', views.UserListView.as_view(), name='list'),

    # URL pattern for the UserRedirectView
    url(r'^~redirect/$', views.UserRedirectView.as_view(), name='redirect'),

    # URL pattern for the UserDetailView
    url(r'^(?P<email>[\w.@+-]+)/$', views.UserDetailView.as_view(), name='detail'),

    # URL pattern for the UserUpdateView
    url(r'^~update/$', views.UserUpdateView.as_view(), name='update'),

    # URL pattern for the UserProfileUpdateView
    url(r'^~profile_update/$', views.ProfileUpdateView.as_view(), name='profile_update'),
    url(r'^~annotations/$', views.UserAnnotationView.as_view(), name='annotations'),
    url(r'^~comments/$', views.UserCommentsView.as_view(), name='comments'),
    url(r'^~draft-bill/$', BillDraftView.as_view(), name='draft-bill'),
    url(r'^~draft-petition/$', PetitionDraftView.as_view(), name='draft-petition'),
]

schedule/urls.py
from django.conf.urls import url
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import (
    CalendarByPeriodsView, CalendarView, EventView,
    OccurrenceView, EditOccurrenceView, DeleteEventView,
    EditEventView, CreateEventView, OccurrencePreview,
    CreateOccurrenceView, CancelOccurrenceView, FullCalendarView,
    api_select_create, api_move_or_resize_by_code, api_occurrences)

urlpatterns = [
    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

dokeza/users/models.py
from __future__ import unicode_literals, absolute_import
from country_dialcode.models import Country, Prefix
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import (
    BaseUserManager, PermissionsMixin, AbstractBaseUser, AbstractUser, AnonymousUser
)
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from .boundaries import KENYAN_CONSTITUENCIES, KENYAN_COUNTIES


class User(AbstractUser):
    """
    This is the 'Base User' for the Dokeza Project. We develop the Standard User, the Institutional User, the Member of Parliament and Mzalendo (Admins).
    username, password, email, first_name, last_name are part
    of the AbstractUser in Django. REQUIRED_FIELDS = ['email']
    """
    # We have added required fields =>
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)
    email = models.EmailField(_('email address'), unique=True)


    # objects = UserManager()

    def __str__(self):
        if self.get_full_name():
            return self.get_full_name()
        else:
            return self.email
    #     
    # def __str__(self):
    #     return self.first_name

    def get_profile(self):
        instance = self
        qs = Profile.objects.filter_by_instance(instance)
        return qs

    def full_name(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'email': self.email})


class Institution(models.Model):
    """
    The Institution class allows for any user to be grouped
    into a corporate organisation. The default is Mzalendo Trust.
    """
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = _('Institution')
        verbose_name_plural = _('Institutions')

    def __str__(self):
        return self.name


class ProfileManager(models.Manager):

    def filter_by_instance(self, instance):
        qs = super(ProfileManager, self).get(user_id=instance.id)
        return qs


class Profile(models.Model):
    """
    This is the extension of each user's profile.
    It incudes all the requirements for all types of users.
    """
    GENDER_CHOICES = (
        (1, 'Male'),
        (2, 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=500, blank=True, null=True)
    gender = models.PositiveSmallIntegerField(
        _('gender'), choices=GENDER_CHOICES, blank=True, null=True)
    picture = models.ImageField(upload_to='profile_pics/',
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    bio = models.TextField(max_length=500, blank=True, null=True)
    county_residence = models.PositiveSmallIntegerField(
        _('County of Residence'), choices=KENYAN_COUNTIES, default=5)
    county_interest = models.PositiveSmallIntegerField(
        _('County of Interest'), choices=KENYAN_COUNTIES, blank=True, null=True)
    # These setting will appear in the Admin, not in the Signup page
    institution = models.ForeignKey(Institution, blank=True, null=True)
    is_editor = models.BooleanField(
        _('editor status'),
        default=False,
        help_text=_(
            'Designates whether the user can create, draft and edit bills.'),)
    is_member_of_parliament = models.BooleanField(
        _('Member of Parliament'), default=False,
        help_text=_('Designates whether the user as an MP in Kenya.'),)
    national_assembly = models.BooleanField(_('National Assembly'),
                                            default=False,)
    constituency = models.PositiveSmallIntegerField(
        _('Constituency'), choices=KENYAN_CONSTITUENCIES,
        blank=True, null=True)
    senate = models.BooleanField(_('Senate'), default=False,)
    county = models.PositiveSmallIntegerField(_('County'),
                                              choices=KENYAN_COUNTIES,
                                              blank=True, null=True
                                              )
    nominated = models.BooleanField(_('Nominated'), default=False,)
    joined = models.DateTimeField(db_index=True, default=datetime.now)
    last_seen = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    twitter = models.URLField(blank=True, null=True)
    # User Mobile Contacts 
    country_code = models.ForeignKey(Prefix, verbose_name=_("Country"), null=True, blank=True, help_text=_("Select Prefix"))
    mobile = models.PositiveIntegerField(blank=True, null=True, help_text=_('Your local mobile number'))
    view_contacts = models.BooleanField(_('Mobile contacts'), default=False, help_text=_('Set this to allow others to see your contacts.'))

    objects = ProfileManager()

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __str__(self):
        try:
            full_name = self.user.get_full_name()
            return full_name
        except:
            self.user.username


@python_2_unicode_compatible
class Visitor(AnonymousUser):
    """
    The Visitor can only view pages open to the public by default.
    """

    def __str__(self):
        return 'Visitor'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

dokeza/templates/users/profile_form.html
{% extends "_layouts/base_user.html" %}

{% load i18n static %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<div class="container user__entry">
  <div class="user__page">
   <h2 class="user__profile">User Profile Details</h2>
    <h3>{{ user.full_name}}</h3>
    <form class="form-horizontal" method="post" action="{% url 'users:profile_update' %}">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="control-group">
        <div class="controls">
         <a href="{% url 'users:update' %}" class="btn btn-secondary ">Back</a>
          <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

dokeza/templates/users/user_detail.html
{% extends "_layouts/base_user.html" %} {% load i18n static %} {% block page_title %}User: {{ object.email }} {% endblock page_title %} {% block content %}
<div class="row justify-content-between">
    <aside class="dz-aside col-sm-4">
        <div class="list-group">
            <div href="#" class="list-group-item justify-content-between list-group-item-warning">
                <h1>Profile</h1>
            </div>
            {% if object.profile.picture %}
            <img class="card-img-top" src=" {% static 'images/{{ object.profile.picture_url }}' %}" alt="{{ request.user.first_name }} {{ request.user.last_name }}"> {% else %} {% if request.user.profile.gender == 1 %}
            <img class="card-img-top" src=" {% static 'images/male_green.svg' %}" alt="{{ request.user.first_name }} {{ request.user.last_name }}"> {% elif request.user.profile.gender == 2 %}
            <img class="card-img-top" src="{% static 'images/female_green.svg' %}" alt="{{ request.user.first_name }} {{ request.user.last_name }}"> {% else %}
            <img class="card-img-top" src=" {% static 'images/male_green.svg' %}" alt="{{ request.user.first_name }} {{ request.user.last_name }}"> {% endif %} {% endif %}
            <div class="list-group-item list-group-item-action justify-content-between">
                {% if object.first_name %}
                <strong>Name</strong>
                <span class="">{{ object.full_name }}</span> {% else %}
                <strong>Username</strong>
                <span class="">{{ object.email }}</span> {% endif %}
            </div>
            <div class="list-group-item list-group-item-action justify-content-between">
                <strong>Joined</strong>
                <span class="">{{ object.profile.joined|date:'d M Y' }}</span>
            </div>
            <div class="list-group-item list-group-item-action justify-content-between">
                <strong>Last Seen</strong>
                <span class="">{{ object.profile.last_seen|date:'d M Y' }}</span>
            </div>
        </div>
        <br>
        <!--Activity-->
        <div class="list-group">
            <div href="#" class="list-group-item justify-content-between list-group-item-info">
                Activity
            </div>
            <a href="#" class="list-group-item list-group-item-action justify-content-between">
                <strong>Annotations</strong>
                <span class="badge badge-info badge-pill">22</span>
            </a>
            <a href="#" class="list-group-item list-group-item-action justify-content-between">
                <strong>Comments</strong>
                <span class="badge badge-info badge-pill">38</span>
            </a>
            <a href="#" class="list-group-item list-group-item-action justify-content-between">
                <strong>Shares</strong>
                <span class="badge badge-info badge-pill">9</span>
            </a>
            <a href="#" class="list-group-item list-group-item-action justify-content-between">
                <strong>Likes</strong>
                <span class="badge badge-info badge-pill">29</span>
            </a>
            <a href="#" class="list-group-item list-group-item-action justify-content-between">
                <strong>Posts</strong>
                <span class="badge badge-info badge-pill">2</span>
            </a>
            <a href="#" class="list-group-item list-group-item-action justify-content-between">
                <strong>Followers</strong>
                <span class="badge badge-info badge-pill">122</span>
            </a>
        </div>
    </aside>
    <article class="col-sm-8">
        <div class="card">
            <div id="my_details" class="card-header {% if object.profile.is_member_of_parliament %}dz-user__mp {% elif object.profile.institution %}dz-user__institution
        {% else %}dz-user__standard {% endif %} alert-info">
                {% if not object.profile %}
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Details</a>
                    </li>
                    <!--
            <li class="nav-item">
              <a class="nav-link active" href="#">Settings</a>
            </li>
            -->
                </ul>
                {% else %}
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Details</span></a>
                    </li>
                    <!--
            <li class="nav-item">
              <a class="nav-link active" href="#">Settings</a>
            </li>
            -->
                </ul>
                {% endif %}
            </div>
            {% if not object.profile %}
            <div id="my_details" class="card-block user__settings">
                {% if object.full_name %}
                <h4 class="card-title">{{ object.full_name }}</h4>
                {% else %}
                <h4 class="card-title">{{ object.email }}</h4>
                {% endif %}
                <h6 class="card-subtitle mb-2 text-muted">{{ object.job_description }}</h6>
                <blockquote class="blockquote">
                    <h6 class="card-subtitle mb-2 text-muted">About</h6>
                    <p class="mb-0 blockquote-footer">
                        {% if not object.profile.bio %}
                        <em>Please add your a short biography.</em> {% else %}
                        <h4 class="card-title">{{ object.email }}</h4>
                        {% endif %}
                    </p>
                    {% if object.profile.institution %}
                    <p>I represent the {{ object.profile.institution }}on this platform.</p>
                    {% endif %} {% if object.profile.is_member_of_parliament and object.profile.national_assembly %}
                    <p>I am the member of the <strong>National Assembly</strong> for <strong>{{ object.profile.get_constituency_display }}</strong> constituency.</p>
                    {% elif object.profile.is_member_of_parliament and object.profile.senate %}
                    <p>I am the member of the <strong>Senate</strong> for <strong>{{ object.profile.get_county_display }}</strong> county.</p>
                    {% endif %}
                    <p class="mb-0 blockquote-footer">County of Residence: {{ object.profile.get_county_residence_display }}</p>
                    <p class="mb-0 blockquote-footer">County of Interest: {{ object.profile.get_county_interest_display }}</p>
                </blockquote>
                <p class="card-text">You can get in touch via the following links:</p>
                <a href="#" class="card-link">Facebook</a>
                <a href="{{ object.twitter }}" class="card-link">Twitter</a>
                <a href="#" class="card-link">Email</a>
                <a href="#" class="card-link">Mobile: 0722 112233 / 0733 112233</a> {% if object == request.user %}
                <!-- Settings buttons -->
                {% if not object.profile %}
                <p>Please fill in your profile details. It will help to filter bills, annotations and comments that match your selections.</p>
                {% endif %}
                <div class="col-sm-12">
                    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Change Profile</a>
                    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Change Email</a>
                </div>
                <!-- End Action buttons -->
                {% endif %}
            </div>
            <div id="my_settings" class="card-block settings__active">
            </div>
            {% else %}
            <div id="my_details" class="card-block">
                {% if object.full_name %}
                <h4 class="card-title">{{ object.full_name }}</h4>
                {% else %}
                <div id="my_details" class="card-block">
                    {% if object.full_name %}
                    <h4 class="card-title">{{ object.full_name }}</h4>
                    {% else %}
                    <h4 class="card-title">{{ object.email }}</h4>
                    {% endif %}
                    </p>
                    {% if object.profile.institution %}
                    <p>I represent the {{ object.profile.institution }}on this platform.</p>
                    {% endif %} {% if object.profile.is_member_of_parliament and object.profile.national_assembly %}
                    <p>I am the member of the <strong>National Assembly</strong> for <strong>{{ object.profile.get_constituency_display }}</strong> constituency.</p>
                    {% elif object.profile.is_member_of_parliament and object.profile.senate %}
                    <p>I am the member of the <strong>Senate</strong> for <strong>{{ object.profile.get_county_display }}</strong> county.</p>
                    {% endif %}
                    <p class="mb-0 blockquote-footer">County of Residence: <strong>{{ object.profile.get_county_residence_display }}</strong></p>
                    <p class="mb-0 blockquote-footer">County of Interest: <strong>{{ object.profile.get_county_interest_display }}</strong></p>
                    </blockquote>
                    <p class="card-text">You can get in touch via the following links:</p>
                    <a href="{{ object.profile.facebook " class="card-link">Facebook</a>
                    <a href="{{ object.profile.twitter }}" target="_blank" class="card-link">Twitter</a>
                    <a href="mailto:{{ object.email }}" class="card-link">Email</a>
                    <a href="" class="card-link">Mobile: {{ object.profile.prefix}} {{ object.profile.mobile }}</a>
                </div>
                <div id="my_settings" class="card-block">
                    {% if object == request.user %}
                    <!-- Settings buttons -->
                    <div class="row">
                        <div class="col-sm-12">
                            <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Change Profile</a>
                            <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Change Email</a>
                            <a class="btn btn-primary" href="{% url 'account_change_password' %}" role="button">Change Password</a>
                        </div>
                    </div>
                    <!-- End Action buttons -->
                    {% endif %}
                </div>
                {% endif %} {% endif %}
    </article>
    </div>
    {% endblock content %}

dokeza/templates/users/user_form.html
{% extends "_layouts/base_user.html" %}

{% load i18n static %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <div class="container user__entry">

  <div class="user__page">
  {% if user.full_name %}
    <h3>Full Name</h3>
    <p>{{ user.full_name }}</p>
    {% else %}
     <h3>Current username</h3>
     <p>{{ user.username }}</p>
  {% endif %}
   
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn btn-primary">Update</button>
            <a href="{% url 'users:profile_update' %}" class="btn btn-secondary">Next</a>
          </div>
        </div>
    </form>
  </div>
  
</div>
{% endblock %}

dokeza/templates/users/user_list.html
{% extends "_layouts/base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>
  {% if not request.user %}
    <p>You must be logged in to see other members.</p>
  {% else %}
    <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.email %}" class="list-group-item">
      {% if user.full_name %}
        <h4 class="list-group-item-heading">{{ user.full_name }}</h4>
      {% else %}
        <h4 class="list-group-item-heading">{{ user.email }}</h4>
      {% endif %}
      </a>
    {% endfor %}
  </div>
  {% endif %}
</div>
{% endblock content %}