bills/api/urls.py
from django.conf.urls import url

from .views import (
    BillCreateAPIView,
    BillDeleteAPIView,
    BillDetailAPIView,
    BillListAPIView,
    BillUpdateAPIView,
)

urlpatterns = [
    url(r'^$', BillListAPIView.as_view(), name='list'),
    url(r'^create/$', BillCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', BillDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', BillUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', BillDeleteAPIView.as_view(), name='delete'),
]
  

bills/urls.py
from django.conf.urls import url

from .views import (
    BillListView,
    AssemblyBillListView,
    SenateBillListView,
    BillDisplayView,
)

urlpatterns = [
    url(r'^$', BillListView.as_view(), name='list'),
    url(r'^assembly/$', AssemblyBillListView.as_view(), name='assembly'),
    url(r'^senate/$', SenateBillListView.as_view(), name='senate'),
    url(r'^(?P<slug>[\w-]+)/$', BillDisplayView.as_view(), name='detail'),
]

cal/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
cal/urls.py

Created by Jimmy Gitonga on 2010-12-28.
Copyright (c) 2010 __MyCompanyName__. All rights reserved.
"""
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^(?P<year>\d{4})/$', CalYearView.as_view(), name='year'),
    url(r'^month/$', CalMonthView.as_view(), name='month'),
    url(r'^month/(?P<year>\d{4})/(?P<month>\d+)/$',
        CalMonthView.as_view(), name='month'),
    url(r'^month/(?P<year>\d{4})/(?P<month>\d+)/(?P<change>\w{4})/$', CalMonthView.as_view(), name='month'),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

from rest_framework_jwt.views import obtain_jwt_token
from dokeza.users.api.views import get_jwt_token
from .views import HomeView, AboutView, HelpView, ContactView, CalendarView, Root, TagIndexView

from annotation import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^help/$', HelpView.as_view(), name='help'),
    url(r'^news/', include('posts.urls', namespace='posts')),
    url(r'^contacts/$', ContactView.as_view(), name='contacts'),
    url(r'^bills/', include('bills.urls', namespace='bills')),
    url(r'^public-participation/', include('public_participation.urls', namespace='public_participation')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('dokeza.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # These are the regular urls.

    # url(r'^annotations/', include('annotation.urls',
    #                               namespace='annotator')),
    url(r'^bills/', include('bills.urls', namespace='bills')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^categories/$', TagIndexView.as_view(), name='categories'),

    url(r'^calendar/', include('cal.urls', namespace='kalenda')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # Annotation URLS
    url(r"^annon_root/$", views.root, name="root"),
    url(r"^annotations/(?P<pk>.+)/?$",
        views.read_update_delete, name="read_update_delete"),
    url(r"^annotations/?$", views.index_create, name="index_create"),
    url(r"^search/?$", views.search, name="search"),
    url(r"^demo/?$", views.DemoView.as_view(), name="demo"),

    # ------- These are the API urls ------------
    # Authentication APIs
    url(r'^api/$', Root),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/auth/token/$', get_jwt_token),
    url(r'^api/users/', include('dokeza.users.api.urls', namespace='users-api')),

    # Access APIs
    url(r'^api/bills/', include('bills.api.urls', namespace='bills-api')),
    url(r'^api/news/', include('posts.api.urls', namespace='posts-api')),
    url(r'^api/comments/', include('comments.api.urls', namespace='comments-api')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

schedule/urls.py
from django.conf.urls import url
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import (
    CalendarByPeriodsView, CalendarView, EventView,
    OccurrenceView, EditOccurrenceView, DeleteEventView,
    EditEventView, CreateEventView, OccurrencePreview,
    CreateOccurrenceView, CancelOccurrenceView, FullCalendarView,
    api_select_create, api_move_or_resize_by_code, api_occurrences)

urlpatterns = [
    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

bills/models.py
# import os
from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.core.urlresolvers import reverse
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from annotation.models import Annotation
from comments.models import Comment

# from PyPDF2 import PdfFileReader
# from wand.image import Image

from taggit.managers import TaggableManager
from hitcount.models import HitCount, HitCountMixin


class Bill(HitCountMixin, models.Model):
    """
    This is the legislative draft bill.

    Description:
    Kenya has two houses in the Parliament, the National Assembly and the Senate. Both houses are sources of draft bills that the Kenyan public are expected to engage with during the Public Participation period.

    The draft bill on this platform has an owner. That could be a member of
    Parliament, or an institutional representative or a member of the public.

    In one case, the owner would like to develop the draft bill and later open
    it up privately to stakeholders and engage with them before the draft bill
    is presented to a house.

    In the second case, a draft bill has been presented to a house of
    Parliament for the first reading and is then put o nthis platform to open
    it up to Public Participation. This bill instance would be owned by the
    Dokeza Platform administrator, in this case, Mzalendo Trust.
    """

    BILL_TYPE = (
        (1, 'National Assembly'),
        (2, 'Senate'),
    )

    SPONSOR_TITLE = (
        (1, 'Member of the National Assembly'),
        (2, 'Senator'),
        (3, 'Leader of Majority Party'),
        (4, 'Leader of Minority Party.'),
        (5, 'Senate Majority Leader'),
        (6, 'Senate Majority Whip'),
        (5, 'Chairperson, Justice and Legal Affairs Committee'),
        (6, 'Chairperson, Committee on Finance, Planning and Trade'),
        (7, 'Chairperson, Budget and Appropriations Committee'),
        (8, 'Chairperson, Committee on Finance, Commerce and Budget'),
        (9, 'Chairman, Administration and National Security'),
        (10, 'Chairperson, Committee on Information and Technology'),
        (11, 'Chairperson, Committee on Education, Research and Technology'),
        (12, 'Chairperson, National Assembly Committee on Health'),
        (13, 'Chairperson, Constituency Development Fund Committee'),
        (14, 'Chairperson, Standing Committee on Energy'),
        (15, 'Chairman, Standing Committee on Health'),
        (16, 'Chairman, Standing Committee on Education'),
        (17, 'Chairperson, Standing Committee on Legal Affairs and Human Rights'),
        (18, 'Chairman, Standing Committee on Labour and Social Welfare'),
        (19, 'Chairman, Sessional Committee on Delegated Legislation'),
        (20, 'Chairman, Senate Ad Hoc Committee on Legislation on Harambee (Voluntary Contribution)'),
        (21, 'Chairperson, Select Committee on Legislation on Royalties Accruing from Natural Resources in the Counties'),
        (22, 'Vice Chairperson, Committee on Information and Technology'),
        (23, 'Member, Committee on Legal Affairs and Human Rights'),
        (24, 'Member, Committee on Justice and Legal Affairs'),
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    bill_from = models.PositiveSmallIntegerField(
        _('Bill from'), choices=BILL_TYPE, default=1, blank=True, null=True)
    title = models.CharField(max_length=100, default='A bill')
    slug = models.SlugField(unique=True)
    purpose = models.TextField(max_length=500, blank=True, null=True)
    sponsor = models.CharField(max_length=500, blank=True, null=True)
    sponsor_title = models.PositiveSmallIntegerField(_('Sponsor Title'), choices=SPONSOR_TITLE, default=1, blank=True, null=True)
    body = RichTextField(
        blank=True,
        help_text="Copy the Bill and paste with all its styling. If necessary use the editing tools to style it sufficiently.")
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    pdf = models.FileField(upload_to='bills/', blank=True, null=True, help_text='Upload the actual bill here.')
    bill_pic = models.ImageField(upload_to='bill_pics/', blank=True, null=True,
                                 help_text='Upload an image of the top stamped page of the bill.')
    private = models.BooleanField(default=True)
    first_reading = models.DateTimeField(auto_now_add=False,
                                         blank=True, null=True)
    second_reading = models.DateTimeField(auto_now_add=False,
                                          blank=True, null=True)
    third_reading = models.DateTimeField(auto_now_add=False,
                                         blank=True, null=True)
    assented_to = models.BooleanField(default=False)
    assented_date = models.DateTimeField(auto_now_add=False,
                                         blank=True, null=True)
    updated_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    law_reference = models.URLField(blank=True, null=True, help_text="This should be a link to the Kenya Law Review repository of the bill.")
    tags = TaggableManager()
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    @property
    def annotations(self):
        instance = self
        qs = Annotation.objects.filter_by_instance(instance)
        return qs

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    def get_absolute_url(self):
        return reverse('bills:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    # ----- This is a implementation of auto-pdf-2-image. It works on the
    # CLI but was problematic to implement in Docker
    # ----------------------------------------------
    # def convert_to_png(self, width=0, height=0):
    #     self.__convert_to_img__(width, height, 'png')

    # def convert_to_jpg(self, width=0, height=0):
    #     self.__convert_to_img__(width, height, 'jpg')

    # def __convert_to_img__(self, width, height, format='jpg'):
    #     size = ''
    #     if width and height:
    #         size = '_' + str(width) + 'x' + str(height) + 'px'

    #     # ---- Where to find the pdf ----
    #     filename = self.pdf.name
    #     filepath = settings.MEDIA_ROOT + '/' + filename
    #     # ----- Where to place the images ------
    #     output_dir = filepath + '_' + format + size + '/'
    #     os.mkdir(output_dir)
    #     # if filename is True:
    #     # else:
    #     #     return ValueError("Please add a pdf to use")
    #     # ---- Activate to read all the pages in the PDF file ----
    #     # input_file = PdfFileReader(file(filepath, 'rb'))
    #     for i in range(3):
    #         with Image(filename=filepath + '[' + str(i) + ']', resolution=300) as img:
    #             if len(size) > 0:
    #                 img.resize(width, height, filter='gaussian')
    #             img.format = format
    #             img.save(filename=output_dir + str(i) + '.' + format)

# --------- Receiver for the Save PDF signal ----------------
# @receiver(post_save, sender=Bill)
# def convert_to_img(sender, instance, **kwargs):
#     print('I have saved')
#     instance.convert_to_png(630, 891)

bills/forms.py
from django import forms

from .models import Bill


class BillForm(forms.ModelForm):

    class Meta:
        model = Bill
        fields = [
            "owner",
            "bill_from",
            "title",
            "body",
            "pdf",
            "private",
        ]

dokeza/templates/bills/base_bill.html
{% extends "_layouts/base.html" %}
{% load static i18n %}

{% block sub-navigation %}
<div class="dz-sub-navigation container-fluid pr-0">
    <nav class="dz-sub-navigation__navbar nav container d-flex flex-nowrap">
        {% include '_partials/sub-navigation/bills.html' %}
    </nav>
</div>
{% endblock sub-navigation %}
{% block breadcrumbs %}<a href="/bills/">Bills</a>{% endblock breadcrumbs %}
{% block pagination %}
<!-- Pagination -->
  <nav aria-label="Page pagination">
      <ul class="pagination pagination-sm justify-content-center">
          <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">Previous</a>
          </li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
              <a class="page-link" href="#">Next</a>
          </li>
      </ul>
  </nav>
<!-- END Pagination -->
{% endblock pagination %}

dokeza/templates/bills/bill_detail.html
{% extends "bills/base_bill.html" %}
{% load static %}
{% load urlify %} {% load crispy_forms_tags %}
{% block title_page %}Bill: {{ object.title }}{% endblock title_page %}
{% block breadcrumbs %} {{ block.super }} » 
  {% if bill.get_bill_from_display|slugify|lower == 'senate' %}
  <a href="{% url 'bills:list' %}">Senate</a> 
  {% else %}<a href="url 'bills:list#national_assembly' ">National Assembly</a> 
  {% endif %} » {{ object.title }}
{% endblock %}

{% block content %}
<!--Main-->
<div class="row justify-content-between">
  <aside class="dz--aside col-sm-4">
    <!--Card-->
    <div class="dz--card_bill">
      <div class="card">
        <h3 class="dz--card_{{ bill.get_bill_from_display|slugify|lower }}-bill card-header">
        {{ object.title }}
        <br><br> {% if bill.get_bill_from_display|slugify|lower == 'senate' %}
          <span class="dz--card_bill-desc">Senate Bill</span> {% else %}
          <span class="dz--card_bill-desc">National Assembly Bill</span> {% endif %}
          </h3>
          <div class="card-block">
            <div class="row">
              <div class="bill-specs col-sm-8">
                <h4 class="card-title">SPONSOR: {{ bill.sponsor }}</h4>
                <p class="bill-dates"><strong>5</strong> Annotations | <strong>{{ bill.comments.count }}</strong> Comments<br />
                <strong>Last updated:</strong> {{bill.updated_date|date:"d M Y"|default:"--"}}</p>
                <p class="bill-actions">
                  Highlight text to <span class="dz--btn_annotate btn btn-primary btn-sm">Annotate</span></p>
                <p class="bill-actions">Click to leave a <a href="#comments" class="dz--btn_comment btn btn-primary btn-sm">Comment</a>
                </p>
              </div>
              <div class="bill-pic">
              {% if object.bill_pic %}
                  <img class="bill-cover" src="{{ object.bill_pic.url }}" alt="" >
              </div>
              {% else %}
                {% if object.bill_from == 1 %}
                  <img class="bill-cover" src="{% static 'images/bill_draft_assembly.svg' %}" alt="">
                {% elif object.bill_from == 2 %}
                   <img class="bill-cover" src="{% static 'images/bill_draft_senate.svg' %}" alt="">
                {% else %}
                  <img class="bill-cover" src="{% static 'images/bill_draft.svg' %}"  alt=""> 
                {% endif %}
              {% endif %}
            </div>
            <hr>
            <p class="card-text">
              <h5 class="dz--aside_heading">{{ bill.title|upper }}</h5>
              <h6 class="dz--aside_title">Clause</h6>
              <ol class="ul">
               {% for list in toc %}
                  {{ list|safe|capfirst }}
                {% endfor %}
              </ol>
            </p>
          </div>
        </div>
      </div>
      <!--END Card-->
    </aside>
    <div class="col-sm-8">
      <h1>{{ object.get_object_from_display }}</h1>
      <h2>{{ object.title }}</h2>
      <div id="content"> {{ object.body|safe }}</div>
      <p>Created on {{ object.created }}</p>
      <p><strong>{{ object.owner.username }}</strong></p>
      <p>{{ object.pdf }}</p>
    </div>
  </div>
  <h6 id="comments" class='lead'>Comments</h6>
  {% if request.user.is_authenticated %}
    <form method="POST" action="."> {% csrf_token %} {{ comment_form|crispy }}
      <input type='submit' value='Post comment' class='btn btn-default'>
    </form>
  {% else %}
    <p>You must login to comment </p>
  {% endif %}
  <hr/> {% for comment in comments %}
    <blockquote>
      <p>{{ comment.content }}</p>
      <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} <a class='comment-reply-btn' href='#'>Reply</a> |
      <a class='' href='{{ comment.get_absolute_url }}'>Thread</a></footer>
      <div class='comment-reply'>
        {% for child_comment in comment.children %}
          <blockquote>
            <p>{{ child_comment.content }}</p>
          <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
        </blockquote>
      {% endfor %} {% if request.user.is_authenticated %}
      <form method="POST" action="."> {% csrf_token %} {{ comment_form|crispy }}
        <input type='hidden' name='parent_id' value='{{ comment.id }}'>
        <input type='submit' value='Reply' class='btn btn-default'>
      </form>
    {% else %}
      <p>You must login to comment </p>
    {% endif %}
  </div>
</blockquote>
<hr/> {% endfor %}
</div>
<!--END Main-->
{% endblock content %}
<!-- Annotator Block -->
{% block annotatorjs %}
<script src="{% static 'dist/js/vendor/annotator.2.0.0.min.js' %}"></script>
<script src="{% static 'dist/js/dokeza-annotator.js' %}"></script>
{% endblock annotatorjs %}

dokeza/templates/bills/bills_list.html
{% extends "bills/base_bill.html" %}
<!-- Main Content -->
{% block content %}
  <div class="row p-3">
    <div class="col-12 col-lg-12">
      <!-- Carousel -->
      <section class="dz-carousel">
        <h1 class="dz-main__heading">Featured Bills</h1>
        <div class="dz-carousel__content">
          <div id="dz-carousel__captions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#dz-carousel__captions" data-slide-to="0" class=""></li>
              <li data-target="#dz-carousel__captions" data-slide-to="1" class="active"></li>
              <li data-target="#dz-carousel__captions" data-slide-to="2" class=""></li>
            </ol>
            <div class="carousel-inner" role="listbox">
            {% for bill in bills|slice:"3" %}
              <div class="carousel-item {% if forloop.first %} active {% endif %}">
                {% if bill.bill_pic %}
                  <img class="img-fluidz" src="{{ bill.bill_pic.url }}" data-holder-rendered="true">
                  <div class="carousel-caption d-none d-md-block">
                    <h3>{{ bill.title }}</h3>
                    <p>{{ bill.purpose }}</p>
                  </div>
                {% else %}
                  {% if bill.bill_from == 1 %}
                   <img class="img-fluidz" src="/static/images/bill_draft_assembly.svg" alt="">
                  {% elif bill.bill_from == 2 %}
                    <img class="img-fluidz" src="/static/images/bill_draft_senate.svg" alt="">
                  {% else %}
                   <img class="img-fluidz" src="/static/images/bill_draft.svg" alt="">
                  {% endif %}
                  <div class="carousel-caption d-none d-md-block">
                    <h3>{{ bill.title }}</h3>
                    <p>{{ bill.purpose }}</p>
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <a class="carousel-control-prev" href="#dz-carousel__captions" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#dz-carousel__captions" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </section>
      <!-- END Carousel -->
      <!-- Bills -->
      <section id="all__bills" class="dz-bills">
        <h1 class="dz-main__heading">Bills open for Public Participation</h1>
        <div class="dz--bills__content col-12">
          <!--Bills-->
          <div class="row">
            {% for bill in bills|slice:"12" %}
              <div class="dz-bills__card col-12 col-sm-4 p-3">
                <div class="card p-1">
                  <a href="{{ bill.get_absolute_url }}">
                    <div class="dz-bills__{{ bill.get_bill_from_display|slugify|lower }} ">
                      <h5 class="bill-heading">{{ bill.title|capfirst }}</h5>
                    </div>
                  </a>
                  <div class="card-block">
                    <p class="bill-sponsor">SPONSOR: {{ bill.sponsor }} <br/>
                    <em>{{ bill.get_sponsor_title_display }}</em></p>
                    <p class="bill-dates"><strong>5</strong> Annotations | <strong>{{ bill.comments.count }}</strong> Comments<br />
                    <strong>Updated:</strong> {{bill.updated_date|date:"d M Y"|default:"--"}}</p>
                    <p class="card-text">{{ bill.purpose|truncatewords:25 }}
                    </p>
                    <a href="{{ bill.get_absolute_url }}" class="btn btn-danger btn-sm">Read more &hellip;</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
          <!--END Bills Cards-->
        </div>
      </section>
      <!-- END Bills Section -->
      <hr>
    </div>
  </div>
{% endblock content%}
<!-- END Main Content -->